import Footer from "./components/Footer";
import Menu from "./components/Menu";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Menu />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
